# Generated by Django 4.2.14 on 2024-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject_app', '0002_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='balck', max_length=100),
        ),
    ]
